name: myconfig
spec:
  listeners:
  - name: listener_httpNEW # 将原有的 http 名称进行修改
    address: 0.0.0.0
    port: 80
    routes:
    - name: local_route
      prefix: /
      clusters:
      - webcluster    
                           
  clusters:                
  - name: webcluster
    endpoints:             
    - address: 172.31.16.11
      port: 80
    - address: 172.31.16.12
      port: 80
