version: '3'

services:
  spire-server:
    build: ./spire-server
    hostname: spire-server
    tty: true
    privileged: true
    networks:
      envoymesh:
        aliases:
          - spire-server

  front-envoy:
    build: ./front-envoy
    hostname: front-envoy
    tty: true
    privileged: true
    volumes:
      - ./front-envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./front-envoy/server.crt:/etc/envoy/certs/server.crt
      - ./front-envoy/server.key:/etc/envoy/certs/server.key
    networks:
      envoymesh:
        ipv4_address: 172.31.95.10
    expose:
      # Expose ports 80 (for general traffic) and 9901 (for the admin server)
      - "80"
      - "443"
      - "9901"

  blue:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - myservice
          - service-blue
          - blue
    environment:
      - SERVICE_NAME=blue
    expose:
      - "80"

  green:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - myservice
          - service-green
          - green
    environment:
      - SERVICE_NAME=green
    expose:
      - "80"

  red:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - myservice
          - service-red
          - red
    environment:
      - SERVICE_NAME=red
    expose:
      - "80"

  service-gray:
    build: ./service-gray
    hostname: service-gray
    tty: true
    privileged: true
    volumes:
      - ./service-gray/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      envoymesh:
        ipv4_address: 172.31.95.11      
        aliases:
          - gray
          - service-gray
    environment:
      - SERVICE_NAME=gray
    expose:
      - "80"
      - "443"

  service-purple:
    build: ./service-purple
    hostname: service-purple
    tty: true
    privileged: true
    volumes:
      - ./service-purple/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      envoymesh:
        ipv4_address: 172.31.95.12      
        aliases:
          - purple
          - service-purple
    environment:
      - SERVICE_NAME=purple
    expose:
      - "80"
      - "443"

networks:
  envoymesh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.95.0/24  
