version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    environment:
    - FRONT_ENVOY_YAML
    networks:
      envoymesh:
        ipv4_address: 172.31.97.10
    expose:
    - "8000"

  ext_authz-http-service:
    build:
      context: ./auth
      dockerfile: http-service/Dockerfile
    volumes:
    - ./users.json:/etc/users.json
    environment:
    - USERS=/etc/users.json
    networks:
    - envoymesh

  ext_authz-grpc-service:
    build:
      context: ./auth
      dockerfile: grpc-service/Dockerfile
    volumes:
    - ./users.json:/etc/users.json
    networks:
    - envoymesh

  ext_authz-opa-service:
    image: openpolicyagent/opa:0.34.1-istio-2
    volumes:
    - ./config/opa-service/policy.rego:/etc/policy.rego
    command:
    - run
    - --log-level=debug
    - --server
    - --log-format=json-pretty
    - --set=plugins.envoy_ext_authz_grpc.addr=:9002
    - --set=decision_logs.console=true
    - /etc/policy.rego
    networks:
    - envoymesh

  upstream-service:
    image: ikubernetes/demoapp:v1.0
    hostname: "upstream-demoapp"
    environment:
    - "PORT=8080"
    networks:
      envoymesh:
        ipv4_address: 172.31.97.11
    expose:
    - "8080"

networks:
  envoymesh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.97.0/24
