version: '3.3'

services:
  spire-server:
    build: ./docker/spire-server
    hostname: spire-server
    tty: true
    privileged: true
    networks:
      envoymesh:
        ipv4_address: 172.31.92.7       
    
  echo:
    build: ./docker/echo
    hostname: echo
    tty: true
    privileged: true
    networks:
      envoymesh:
        ipv4_address: 172.31.92.6      
    links:
      - spire-server

  web:
    build: ./docker/web
    hostname: web
    tty: true
    privileged: true
    networks:
      envoymesh:
        ipv4_address: 172.31.92.5
    links:
      - spire-server
      - echo
    ports:
      - 8080:8080

networks:
  envoymesh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.92.0/24      
